### ISSUE TITLE
Convert k instead of adding 000 multiply by 1000

### ISSUE THREAD

**Issue by JustGuardian** [acmesecorg/metacrack#2]
Now while using meta split, when I run like 3kk it adds 000000 to the 3 resulting in 3000000. The problem is that if I put 2.5kk it will fail cause it will add 000000 to 2.5 resulting in 2.5000000. Probably the best way to fix this is, instead of adding 000 when k is written, multiply the number by 1000. In this way if I have 2.5kk meta will read 2.5*1000*1000=2500000.

**Comment by jameswestgate** [comment]
Fixed in https://github.com/acmesecorg/metacrack/commit/39118757ee5c7ec1edd0e328369998602781873b.
Will be released in version 1.2.1
